//$file${HSMs::./src::ClockAlarm_SM.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: model.qm
// File:  ${HSMs::./src::ClockAlarm_SM.c}
//
// This code has been generated by QM 6.2.3 <www.state-machine.com/qm>.
// DO NOT EDIT SECTIONS BETWEEN THE COMMENTS "$...vvv".."$end...^^^".
// All your changes in these sections will be lost.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// Copyright (c) 2005 Quantum Leaps, LLC
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for licensees
// interested in retaining the proprietary status of the generated code.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${HSMs::./src::ClockAlarm_SM.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpc.h"
#include "bsp.h" // display
#include "ClockAlarm_SM.h"
#include "stm32wbxx_hal.h"

// PROTOTYPES FOR HELPER FUNCTIONS
const char* get_am_or_pm(uint32_t time24h);
uint32_t convert_12hformat_to_24h(uint32_t time12h, time_format_t ampm);
uint32_t convert_24hformat_to_12h(uint32_t time24h);
bool is_time_set_error(uint32_t time_, time_format_t format);

//$declare${HSMs::Clock_Alarm} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${HSMs::Clock_Alarm} .......................................................
typedef struct Clock_Alarm {
// protected:
    QHsm super;

// private:
    uint32_t temp_time;
    uint32_t alarm_time;
    uint8_t alarm_status;
    uint8_t time_mode;
    uint8_t temp_format;
    uint8_t temp_digit;

// public:
    uint16_t alarm_timeout;
    uint8_t timeout;

// private state histories
    QStateHandler hist_Clock;
} Clock_Alarm;

extern uint32_t Clock_Alarm_curr_time;

extern Clock_Alarm Clock_Alarm_obj;

// public:
static uint32_t Clock_Alarm_get_curr_time(void);
static void Clock_Alarm_update_curr_time(void);
static void Clock_Alarm_set_curr_time(uint32_t new_curr_time);
static void Clock_Alarm_display_curr_time(Clock_Alarm * const me,
    uint8_t row,
    uint8_t col);
static void Clock_Alarm_display_clock_setting_time(Clock_Alarm * const me,
    uint8_t row,
    uint8_t col);

// protected:
static QState Clock_Alarm_initial(Clock_Alarm * const me, void const * const par);
static QState Clock_Alarm_Clock(Clock_Alarm * const me, QEvt const * const e);
static QState Clock_Alarm_Ticking(Clock_Alarm * const me, QEvt const * const e);
static QState Clock_Alarm_Settings(Clock_Alarm * const me, QEvt const * const e);
static QState Clock_Alarm_Alarm_Setting(Clock_Alarm * const me, QEvt const * const e);
static QState Clock_Alarm_as_hour_d1(Clock_Alarm * const me, QEvt const * const e);
static QState Clock_Alarm_as_hour_d2(Clock_Alarm * const me, QEvt const * const e);
static QState Clock_Alarm_as_min_d1(Clock_Alarm * const me, QEvt const * const e);
static QState Clock_Alarm_as_min_d2(Clock_Alarm * const me, QEvt const * const e);
static QState Clock_Alarm_as_sec_d1(Clock_Alarm * const me, QEvt const * const e);
static QState Clock_Alarm_as_sec_d2(Clock_Alarm * const me, QEvt const * const e);
static QState Clock_Alarm_as_format(Clock_Alarm * const me, QEvt const * const e);
static QState Clock_Alarm_as_error(Clock_Alarm * const me, QEvt const * const e);
static QState Clock_Alarm_alarm_on_off(Clock_Alarm * const me, QEvt const * const e);
static QState Clock_Alarm_cs_hour_d2(Clock_Alarm * const me, QEvt const * const e);
static QState Clock_Alarm_cs_sec_d2(Clock_Alarm * const me, QEvt const * const e);
static QState Clock_Alarm_cs_hour_d1(Clock_Alarm * const me, QEvt const * const e);
static QState Clock_Alarm_cs_error(Clock_Alarm * const me, QEvt const * const e);
static QState Clock_Alarm_cs_sec_d1(Clock_Alarm * const me, QEvt const * const e);
static QState Clock_Alarm_cs_format(Clock_Alarm * const me, QEvt const * const e);
static QState Clock_Alarm_cs_min_d2(Clock_Alarm * const me, QEvt const * const e);
static QState Clock_Alarm_cs_min_d1(Clock_Alarm * const me, QEvt const * const e);
static QState Clock_Alarm_Clock_Setting(Clock_Alarm * const me, QEvt const * const e);
static QState Clock_Alarm_Alarm_Notify(Clock_Alarm * const me, QEvt const * const e);
static QState Clock_Alarm_alarm_msg_on(Clock_Alarm * const me, QEvt const * const e);
static QState Clock_Alarm_alarm_msg_off(Clock_Alarm * const me, QEvt const * const e);
//$enddecl${HSMs::Clock_Alarm} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${HSMs::super_ClockAlarm} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${HSMs::super_ClockAlarm} ..................................................
QHsm *const super_ClockAlarm = &Clock_Alarm_obj.super;
//$enddef${HSMs::super_ClockAlarm} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${HSMs::Clock_Alarm_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${HSMs::Clock_Alarm_ctor} ..................................................
void Clock_Alarm_ctor(void) {
    QHsm_ctor(&Clock_Alarm_obj.super, Q_STATE_CAST(&Clock_Alarm_initial));
}
//$enddef${HSMs::Clock_Alarm_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${HSMs::Clock_Alarm} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${HSMs::Clock_Alarm} .......................................................
uint32_t Clock_Alarm_curr_time;
Clock_Alarm Clock_Alarm_obj;

//${HSMs::Clock_Alarm::get_curr_time} ........................................
static uint32_t Clock_Alarm_get_curr_time(void) {
    return Clock_Alarm_curr_time;
}

//${HSMs::Clock_Alarm::update_curr_time} .....................................
static void Clock_Alarm_update_curr_time(void) {
    if(++Clock_Alarm_curr_time == MAX_TIME) {
        Clock_Alarm_curr_time = 0;
    }
}

//${HSMs::Clock_Alarm::set_curr_time} ........................................
static void Clock_Alarm_set_curr_time(uint32_t new_curr_time) {
    Clock_Alarm_curr_time = new_curr_time;
}

//${HSMs::Clock_Alarm::display_curr_time} ....................................
static void Clock_Alarm_display_curr_time(Clock_Alarm * const me,
    uint8_t row,
    uint8_t col)
{
    char time_as_string[16];

    // 1. Descomentado: Precisamos do time24h para extrair o AM/PM lá embaixo
    uint32_t total_ticks = Clock_Alarm_get_curr_time();
    uint32_t time24h = total_ticks / 10;
    uint8_t ss = total_ticks % 10U;

    // 2. Descomentado: Mantém a sua lógica original de conversão 12H/24H
    uint32_t time_ = (me->time_mode == MODE_24H) ? time24h : convert_24hformat_to_12h(time24h);

    // 3. Adicionado: Precisamos extrair as horas, minutos e segundos da variável 'time_'
    // (Ajuste o nome dessas macros caso sejam diferentes no seu projeto)
    uint8_t h = GET_HOUR(time_);
    uint8_t m = GET_MIN(time_);
    uint8_t s = GET_SEC(time_);

    /* if mode is 12H, concatenate am/pm information */
    if(me->time_mode == MODE_12H) {
        const char* am_pm = get_am_or_pm(time24h);

        // Corrigido: adicionada a vírgula entre 'm' e 's'
        snprintf(time_as_string, sizeof(time_as_string), "%02u:%02u:%02u:%02u %s", h, m, s, ss, am_pm);
    } else {
        // Corrigido: adicionada a vírgula entre 'm' e 's'
        snprintf(time_as_string, sizeof(time_as_string), "%02u:%02u:%02u:%02u", h, m, s, ss);
    }

    bsp_display_write_string(row, col, time_as_string);

}

//${HSMs::Clock_Alarm::display_clock_setting_time} ...........................
static void Clock_Alarm_display_clock_setting_time(Clock_Alarm * const me,
    uint8_t row,
    uint8_t col)
{
    char time_as_string[20];

    uint8_t h = GET_HOUR(me->temp_time);
    uint8_t m = GET_MIN(me->temp_time);
    uint8_t s = GET_SEC(me->temp_time);

    const char* am_pm;

    if(me->temp_format != FORMAT_24H) {
        am_pm = (me->temp_format == FORMAT_AM) ? "AM" : "PM";

        snprintf(time_as_string, sizeof(time_as_string), "%02u:%02u:%02u %s", h, m, s, am_pm);

    } else {
        am_pm = " 24H";
        snprintf(time_as_string, sizeof(time_as_string), "%02u:%02u:%02u%s", h, m, s, am_pm);
    }

    bsp_display_write_string(row, col, time_as_string);
}

//${HSMs::Clock_Alarm::SM} ...................................................
static QState Clock_Alarm_initial(Clock_Alarm * const me, void const * const par) {
    //${HSMs::Clock_Alarm::SM::initial}
    Clock_Alarm_set_curr_time(INITIAL_CURR_TIME);
    me->alarm_time = INITIAL_ALARM_TIME;
    me->time_mode = MODE_12H;
    me->alarm_status = ALARM_OFF;
    // state history attributes
    me->hist_Clock = Q_STATE_CAST(&Clock_Alarm_Ticking);
    return Q_TRAN(&Clock_Alarm_Ticking);
}

//${HSMs::Clock_Alarm::SM::Clock} ............................................
static QState Clock_Alarm_Clock(Clock_Alarm * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${HSMs::Clock_Alarm::SM::Clock}
        case Q_EXIT_SIG: {
            // save deep history
            me->hist_Clock = QHsm_state(Q_HSM_UPCAST(me));
            status_ = Q_HANDLED();
            break;
        }
        //${HSMs::Clock_Alarm::SM::Clock::ALARM}
        case ALARM_SIG: {
            //${HSMs::Clock_Alarm::SM::Clock::ALARM::[(me->alarm_status==ALARM_ON&&((~}
            if ((me->alarm_status == ALARM_ON && ((Clock_Alarm_get_curr_time() / 10) == me->alarm_time))) {
                status_ = Q_TRAN(&Clock_Alarm_Alarm_Notify);
            }
            else {
                status_ = Q_UNHANDLED();
            }
            break;
        }
        //${HSMs::Clock_Alarm::SM::Clock::TICK}
        case TICK_SIG: {
            Clock_Alarm_update_curr_time();
            Clock_Alarm_display_curr_time(me, TICKING_CURR_TIME_ROW, TICKING_CURR_TIME_COL);
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${HSMs::Clock_Alarm::SM::Clock::Ticking} ...................................
static QState Clock_Alarm_Ticking(Clock_Alarm * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${HSMs::Clock_Alarm::SM::Clock::Ticking}
        case Q_ENTRY_SIG: {
            Clock_Alarm_display_curr_time(me, TICKING_CURR_TIME_ROW, TICKING_CURR_TIME_COL);
            status_ = Q_HANDLED();
            break;
        }
        //${HSMs::Clock_Alarm::SM::Clock::Ticking::SET}
        case SET_SIG: {
            me->temp_time = Clock_Alarm_get_curr_time() / 10;
            if (me->time_mode == MODE_12H) {
                if(strcmp(get_am_or_pm(me->temp_time), "AM") == 0)
                    me->temp_format = FORMAT_AM;
                else
                    me->temp_time = convert_24hformat_to_12h(me->temp_time);
                me->temp_time = convert_24hformat_to_12h(me->temp_time);

            } else {

                me->temp_format = FORMAT_24H;
            }
            status_ = Q_TRAN(&Clock_Alarm_Clock_Setting);
            break;
        }
        //${HSMs::Clock_Alarm::SM::Clock::Ticking::OK}
        case OK_SIG: {
            me->temp_time = me->alarm_time;
            if (me->time_mode == MODE_12H) {
                if(strcmp(get_am_or_pm(me->temp_time), "AM") == 0)
                    me->temp_format = FORMAT_AM;
                else
                    me->temp_format = FORMAT_PM;

                me->temp_time = convert_24hformat_to_12h(me->temp_time);
            } else {

                me->temp_format = FORMAT_24H;
            }
            status_ = Q_TRAN(&Clock_Alarm_Alarm_Setting);
            break;
        }
        //${HSMs::Clock_Alarm::SM::Clock::Ticking::TICK}
        case TICK_SIG: {
            Clock_Alarm_update_curr_time();
            Clock_Alarm_display_curr_time(me, TICKING_CURR_TIME_ROW, TICKING_CURR_TIME_COL);
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&Clock_Alarm_Clock);
            break;
        }
    }
    return status_;
}

//${HSMs::Clock_Alarm::SM::Clock::Settings} ..................................
static QState Clock_Alarm_Settings(Clock_Alarm * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${HSMs::Clock_Alarm::SM::Clock::Settings}
        case Q_EXIT_SIG: {
            bsp_display_clear();
            status_ = Q_HANDLED();
            break;
        }
        //${HSMs::Clock_Alarm::SM::Clock::Settings::initial}
        case Q_INIT_SIG: {
            bsp_display_clear();
            Clock_Alarm_display_clock_setting_time(me, CLOCK_SETTING_TIME_ROW, CLOCK_SETTING_TIME_COL);
            status_ = Q_TRAN(&Clock_Alarm_cs_hour_d1);
            break;
        }
        //${HSMs::Clock_Alarm::SM::Clock::Settings::ABRT}
        case ABRT_SIG: {
            bsp_display_clear();
            status_ = Q_TRAN(&Clock_Alarm_Ticking);
            break;
        }
        //${HSMs::Clock_Alarm::SM::Clock::Settings::OK}
        case OK_SIG: {
            status_ = Q_TRAN(&Clock_Alarm_Ticking);
            break;
        }
        default: {
            status_ = Q_SUPER(&Clock_Alarm_Clock);
            break;
        }
    }
    return status_;
}

//${HSMs::Clock_Alarm::SM::Clock::Settings::Alarm_Setting} ...................
static QState Clock_Alarm_Alarm_Setting(Clock_Alarm * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${HSMs::Clock_Alarm::SM::Clock::Settings::Alarm_Setting::initial}
        case Q_INIT_SIG: {
            bsp_display_clear();
            Clock_Alarm_display_clock_setting_time(me, CLOCK_SETTING_TIME_ROW, CLOCK_SETTING_TIME_COL);
            status_ = Q_TRAN(&Clock_Alarm_as_hour_d1);
            break;
        }
        //${HSMs::Clock_Alarm::SM::Clock::Settings::Alarm_Setting::OK}
        case OK_SIG: {
            me->alarm_status = me->temp_digit;
            if (me->temp_format != FORMAT_24H) {
                me->temp_time = convert_12hformat_to_24h(me->temp_time, (time_format_t) me->temp_format);
            }

            me->alarm_time = me->temp_time;
            //${HSMs::Clock_Alarm::SM::Clock::Settings::Alarm_Setting::OK::[0]}
            if (0) {
                status_ = Q_HANDLED();
            }
            else {
                status_ = Q_UNHANDLED();
            }
            break;
        }
        default: {
            status_ = Q_SUPER(&Clock_Alarm_Settings);
            break;
        }
    }
    return status_;
}

//${HSMs::Clock_Alarm::SM::Clock::Settings::Alarm_Setting::as_hour_d1} .......
static QState Clock_Alarm_as_hour_d1(Clock_Alarm * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${HSMs::Clock_Alarm::SM::Clock::Settings::Alarm_Setting::as_hour_d1}
        case Q_ENTRY_SIG: {
            me->temp_digit = DIGIT1(GET_HOUR(me->temp_time));
            status_ = Q_HANDLED();
            break;
        }
        //${HSMs::Clock_Alarm::SM::Clock::Settings::Alarm_Setting::as_hour_d1::SET}
        case SET_SIG: {
            ++me->temp_digit;
            me->temp_digit %= 3;
            me->temp_time -= DIGIT1(GET_HOUR(me->temp_time)) * 10UL * 3600UL;
            me->temp_time += (me->temp_digit * 10UL) * 3600UL;
            Clock_Alarm_display_clock_setting_time(me, 0, 2);
            status_ = Q_HANDLED();
            break;
        }
        //${HSMs::Clock_Alarm::SM::Clock::Settings::Alarm_Setting::as_hour_d1::OK}
        case OK_SIG: {
            status_ = Q_TRAN(&Clock_Alarm_as_hour_d2);
            break;
        }
        default: {
            status_ = Q_SUPER(&Clock_Alarm_Alarm_Setting);
            break;
        }
    }
    return status_;
}

//${HSMs::Clock_Alarm::SM::Clock::Settings::Alarm_Setting::as_hour_d2} .......
static QState Clock_Alarm_as_hour_d2(Clock_Alarm * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${HSMs::Clock_Alarm::SM::Clock::Settings::Alarm_Setting::as_hour_d2}
        case Q_ENTRY_SIG: {
            me->temp_digit = DIGIT2(GET_HOUR(me->temp_time));
            status_ = Q_HANDLED();
            break;
        }
        //${HSMs::Clock_Alarm::SM::Clock::Settings::Alarm_Setting::as_hour_d2::OK}
        case OK_SIG: {
            status_ = Q_TRAN(&Clock_Alarm_as_min_d1);
            break;
        }
        //${HSMs::Clock_Alarm::SM::Clock::Settings::Alarm_Setting::as_hour_d2::SET}
        case SET_SIG: {
            ++me->temp_digit;
            me->temp_digit %= 10;
            me->temp_time -= DIGIT2(GET_HOUR(me->temp_time)) * 3600UL;
            me->temp_time += (me->temp_digit) * 3600UL;
            Clock_Alarm_display_clock_setting_time(me, 0, 2);
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&Clock_Alarm_Alarm_Setting);
            break;
        }
    }
    return status_;
}

//${HSMs::Clock_Alarm::SM::Clock::Settings::Alarm_Setting::as_min_d1} ........
static QState Clock_Alarm_as_min_d1(Clock_Alarm * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${HSMs::Clock_Alarm::SM::Clock::Settings::Alarm_Setting::as_min_d1}
        case Q_ENTRY_SIG: {
            me->temp_digit = DIGIT1(GET_MIN(me->temp_time));
            status_ = Q_HANDLED();
            break;
        }
        //${HSMs::Clock_Alarm::SM::Clock::Settings::Alarm_Setting::as_min_d1::OK}
        case OK_SIG: {
            status_ = Q_TRAN(&Clock_Alarm_as_min_d2);
            break;
        }
        //${HSMs::Clock_Alarm::SM::Clock::Settings::Alarm_Setting::as_min_d1::SET}
        case SET_SIG: {
            ++me->temp_digit;
            me->temp_digit %= 6;
            me->temp_time -= DIGIT1(GET_MIN(me->temp_time)) * 10UL * 60UL;
            me->temp_time += (me->temp_digit)  * 10UL * 60UL;
            Clock_Alarm_display_clock_setting_time(me, CLOCK_SETTING_TIME_ROW, CLOCK_SETTING_TIME_COL);
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&Clock_Alarm_Alarm_Setting);
            break;
        }
    }
    return status_;
}

//${HSMs::Clock_Alarm::SM::Clock::Settings::Alarm_Setting::as_min_d2} ........
static QState Clock_Alarm_as_min_d2(Clock_Alarm * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${HSMs::Clock_Alarm::SM::Clock::Settings::Alarm_Setting::as_min_d2}
        case Q_ENTRY_SIG: {
            me->temp_digit = DIGIT2(GET_MIN(me->temp_time));
            status_ = Q_HANDLED();
            break;
        }
        //${HSMs::Clock_Alarm::SM::Clock::Settings::Alarm_Setting::as_min_d2::OK}
        case OK_SIG: {
            status_ = Q_TRAN(&Clock_Alarm_as_sec_d1);
            break;
        }
        //${HSMs::Clock_Alarm::SM::Clock::Settings::Alarm_Setting::as_min_d2::SET}
        case SET_SIG: {
            ++me->temp_digit;
            me->temp_digit %= 10;
            me->temp_time -= DIGIT2(GET_MIN(me->temp_time)) * 60UL;
            me->temp_time += (me->temp_digit) * 60UL;
            Clock_Alarm_display_clock_setting_time(me, CLOCK_SETTING_TIME_ROW, CLOCK_SETTING_TIME_COL);
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&Clock_Alarm_Alarm_Setting);
            break;
        }
    }
    return status_;
}

//${HSMs::Clock_Alarm::SM::Clock::Settings::Alarm_Setting::as_sec_d1} ........
static QState Clock_Alarm_as_sec_d1(Clock_Alarm * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${HSMs::Clock_Alarm::SM::Clock::Settings::Alarm_Setting::as_sec_d1}
        case Q_ENTRY_SIG: {
            me->temp_digit = DIGIT1(GET_SEC(me->temp_time));
            status_ = Q_HANDLED();
            break;
        }
        //${HSMs::Clock_Alarm::SM::Clock::Settings::Alarm_Setting::as_sec_d1::OK}
        case OK_SIG: {
            status_ = Q_TRAN(&Clock_Alarm_as_sec_d2);
            break;
        }
        //${HSMs::Clock_Alarm::SM::Clock::Settings::Alarm_Setting::as_sec_d1::SET}
        case SET_SIG: {
            ++me->temp_digit;
            me->temp_digit %= 6;
            me->temp_time -= DIGIT1(GET_SEC(me->temp_time)) * 10UL;
            me->temp_time += me->temp_digit * 10UL;
            Clock_Alarm_display_clock_setting_time(me, CLOCK_SETTING_TIME_ROW, CLOCK_SETTING_TIME_COL);
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&Clock_Alarm_Alarm_Setting);
            break;
        }
    }
    return status_;
}

//${HSMs::Clock_Alarm::SM::Clock::Settings::Alarm_Setting::as_sec_d2} ........
static QState Clock_Alarm_as_sec_d2(Clock_Alarm * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${HSMs::Clock_Alarm::SM::Clock::Settings::Alarm_Setting::as_sec_d2}
        case Q_ENTRY_SIG: {
            me->temp_digit = DIGIT2(GET_SEC(me->temp_time));
            status_ = Q_HANDLED();
            break;
        }
        //${HSMs::Clock_Alarm::SM::Clock::Settings::Alarm_Setting::as_sec_d2::OK}
        case OK_SIG: {
            status_ = Q_TRAN(&Clock_Alarm_as_format);
            break;
        }
        //${HSMs::Clock_Alarm::SM::Clock::Settings::Alarm_Setting::as_sec_d2::SET}
        case SET_SIG: {
            ++me->temp_digit;
            me->temp_digit %= 10;
            me->temp_time -= DIGIT2(GET_SEC(me->temp_time));
            me->temp_time += me->temp_digit;
            Clock_Alarm_display_clock_setting_time(me, CLOCK_SETTING_TIME_ROW, CLOCK_SETTING_TIME_COL);
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&Clock_Alarm_Alarm_Setting);
            break;
        }
    }
    return status_;
}

//${HSMs::Clock_Alarm::SM::Clock::Settings::Alarm_Setting::as_format} ........
static QState Clock_Alarm_as_format(Clock_Alarm * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${HSMs::Clock_Alarm::SM::Clock::Settings::Alarm_Setting::as_format::SET}
        case SET_SIG: {
            if (me->temp_format == FORMAT_24H) {
                me->temp_format = FORMAT_AM;
            } else if(me->temp_format == FORMAT_AM) {
                me->temp_format = FORMAT_PM;
            } else if(me->temp_format == FORMAT_PM) {
                me->temp_format = FORMAT_24H;
            }
            Clock_Alarm_display_clock_setting_time(me, CLOCK_SETTING_TIME_ROW, CLOCK_SETTING_TIME_COL);
            status_ = Q_HANDLED();
            break;
        }
        //${HSMs::Clock_Alarm::SM::Clock::Settings::Alarm_Setting::as_format::OK}
        case OK_SIG: {
            //${HSMs::Clock_Alarm::SM::Clock::Settings::Alarm_Setting::as_format::OK::[is_time_set_error(me->temp_time~}
            if (is_time_set_error(me->temp_time, (time_format_t) me->temp_format)) {
                status_ = Q_TRAN(&Clock_Alarm_as_error);
            }
            //${HSMs::Clock_Alarm::SM::Clock::Settings::Alarm_Setting::as_format::OK::[else]}
            else {
                status_ = Q_TRAN(&Clock_Alarm_alarm_on_off);
            }
            break;
        }
        default: {
            status_ = Q_SUPER(&Clock_Alarm_Alarm_Setting);
            break;
        }
    }
    return status_;
}

//${HSMs::Clock_Alarm::SM::Clock::Settings::Alarm_Setting::as_error} .........
static QState Clock_Alarm_as_error(Clock_Alarm * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${HSMs::Clock_Alarm::SM::Clock::Settings::Alarm_Setting::as_error}
        case Q_ENTRY_SIG: {
            bsp_display_clear();
            bsp_display_write_string(0, 0, "ERROR");
            status_ = Q_HANDLED();
            break;
        }
        //${HSMs::Clock_Alarm::SM::Clock::Settings::Alarm_Setting::as_error::OK}
        case OK_SIG: {
            status_ = Q_HANDLED();
            break;
        }
        //${HSMs::Clock_Alarm::SM::Clock::Settings::Alarm_Setting::as_error::SET}
        case SET_SIG: {
            status_ = Q_TRAN(&Clock_Alarm_Alarm_Setting);
            break;
        }
        default: {
            status_ = Q_SUPER(&Clock_Alarm_Alarm_Setting);
            break;
        }
    }
    return status_;
}

//${HSMs::Clock_Alarm::SM::Clock::Settings::Alarm_Setting::alarm_on_off} .....
static QState Clock_Alarm_alarm_on_off(Clock_Alarm * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${HSMs::Clock_Alarm::SM::Clock::Settings::Alarm_Setting::alarm_on_off}
        case Q_ENTRY_SIG: {
            me->temp_digit = 0U;
            bsp_display_write_string(0, 15, "ALARM OFF");
            status_ = Q_HANDLED();
            break;
        }
        //${HSMs::Clock_Alarm::SM::Clock::Settings::Alarm_Setting::alarm_on_off::SET}
        case SET_SIG: {
            if(me->temp_digit) {
                bsp_display_write_string(0, 15, "ALARM OFF");
                me->temp_digit = 0;
            } else {
                bsp_display_write_string(0, 15, "ALARM ON");
                me->temp_digit = 1;
            }
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&Clock_Alarm_Alarm_Setting);
            break;
        }
    }
    return status_;
}

//${HSMs::Clock_Alarm::SM::Clock::Settings::cs_hour_d2} ......................
static QState Clock_Alarm_cs_hour_d2(Clock_Alarm * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${HSMs::Clock_Alarm::SM::Clock::Settings::cs_hour_d2}
        case Q_ENTRY_SIG: {
            me->temp_digit = DIGIT2(GET_HOUR(me->temp_time));
            status_ = Q_HANDLED();
            break;
        }
        //${HSMs::Clock_Alarm::SM::Clock::Settings::cs_hour_d2::SET}
        case SET_SIG: {
            ++me->temp_digit;
            me->temp_digit %= 10;
            me->temp_time -= DIGIT2(GET_HOUR(me->temp_time)) * 3600UL;
            me->temp_time += (me->temp_digit) * 3600UL;
            Clock_Alarm_display_clock_setting_time(me, 0, 2);
            // display_set_cursor(CS_ROW, CLOCK_SETTING_TIME_HOUR_D2);
            status_ = Q_HANDLED();
            break;
        }
        //${HSMs::Clock_Alarm::SM::Clock::Settings::cs_hour_d2::OK}
        case OK_SIG: {
            status_ = Q_TRAN(&Clock_Alarm_cs_min_d1);
            break;
        }
        default: {
            status_ = Q_SUPER(&Clock_Alarm_Settings);
            break;
        }
    }
    return status_;
}

//${HSMs::Clock_Alarm::SM::Clock::Settings::cs_sec_d2} .......................
static QState Clock_Alarm_cs_sec_d2(Clock_Alarm * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${HSMs::Clock_Alarm::SM::Clock::Settings::cs_sec_d2}
        case Q_ENTRY_SIG: {
            me->temp_digit = DIGIT2(GET_SEC(me->temp_time));
            status_ = Q_HANDLED();
            break;
        }
        //${HSMs::Clock_Alarm::SM::Clock::Settings::cs_sec_d2::OK}
        case OK_SIG: {
            status_ = Q_TRAN(&Clock_Alarm_cs_format);
            break;
        }
        //${HSMs::Clock_Alarm::SM::Clock::Settings::cs_sec_d2::SET}
        case SET_SIG: {
            ++me->temp_digit;
            me->temp_digit %= 10;
            me->temp_time -= DIGIT2(GET_SEC(me->temp_time));
            me->temp_time += me->temp_digit;
            Clock_Alarm_display_clock_setting_time(me, CLOCK_SETTING_TIME_ROW, CLOCK_SETTING_TIME_COL);
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&Clock_Alarm_Settings);
            break;
        }
    }
    return status_;
}

//${HSMs::Clock_Alarm::SM::Clock::Settings::cs_hour_d1} ......................
static QState Clock_Alarm_cs_hour_d1(Clock_Alarm * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${HSMs::Clock_Alarm::SM::Clock::Settings::cs_hour_d1}
        case Q_ENTRY_SIG: {
            //display_set_cursor(CLOCK_SETTING_TIME_ROW, CLOCK_SETTING_TIME_HOUR_D1_COL);
            bsp_write_rect();
            me->temp_digit = DIGIT1(GET_HOUR(me->temp_time));
            status_ = Q_HANDLED();
            break;
        }
        //${HSMs::Clock_Alarm::SM::Clock::Settings::cs_hour_d1::SET}
        case SET_SIG: {
            ++me->temp_digit;
            me->temp_digit %= 3;
            me->temp_time -= DIGIT1(GET_HOUR(me->temp_time)) * 10UL * 3600UL;
            me->temp_time += (me->temp_digit * 10UL) * 3600UL;
            Clock_Alarm_display_clock_setting_time(me, 0, 2);
            // display_set_cursor(CS_ROW, CLOCK_SETTING_TIME_HOUR_D1);
            status_ = Q_HANDLED();
            break;
        }
        //${HSMs::Clock_Alarm::SM::Clock::Settings::cs_hour_d1::OK}
        case OK_SIG: {
            status_ = Q_TRAN(&Clock_Alarm_cs_hour_d2);
            break;
        }
        default: {
            status_ = Q_SUPER(&Clock_Alarm_Settings);
            break;
        }
    }
    return status_;
}

//${HSMs::Clock_Alarm::SM::Clock::Settings::cs_error} ........................
static QState Clock_Alarm_cs_error(Clock_Alarm * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${HSMs::Clock_Alarm::SM::Clock::Settings::cs_error}
        case Q_ENTRY_SIG: {
            bsp_display_clear();
            bsp_display_write_string(0, 0, "ERROR");
            status_ = Q_HANDLED();
            break;
        }
        //${HSMs::Clock_Alarm::SM::Clock::Settings::cs_error::SET}
        case SET_SIG: {
            status_ = Q_TRAN(&Clock_Alarm_Clock_Setting);
            break;
        }
        //${HSMs::Clock_Alarm::SM::Clock::Settings::cs_error::OK}
        case OK_SIG: {
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&Clock_Alarm_Settings);
            break;
        }
    }
    return status_;
}

//${HSMs::Clock_Alarm::SM::Clock::Settings::cs_sec_d1} .......................
static QState Clock_Alarm_cs_sec_d1(Clock_Alarm * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${HSMs::Clock_Alarm::SM::Clock::Settings::cs_sec_d1}
        case Q_ENTRY_SIG: {
            me->temp_digit = DIGIT1(GET_SEC(me->temp_time));
            status_ = Q_HANDLED();
            break;
        }
        //${HSMs::Clock_Alarm::SM::Clock::Settings::cs_sec_d1::SET}
        case SET_SIG: {
            ++me->temp_digit;
            me->temp_digit %= 6;
            me->temp_time -= DIGIT1(GET_SEC(me->temp_time)) * 10UL;
            me->temp_time += me->temp_digit * 10UL;
            Clock_Alarm_display_clock_setting_time(me, CLOCK_SETTING_TIME_ROW, CLOCK_SETTING_TIME_COL);
            status_ = Q_HANDLED();
            break;
        }
        //${HSMs::Clock_Alarm::SM::Clock::Settings::cs_sec_d1::OK}
        case OK_SIG: {
            status_ = Q_TRAN(&Clock_Alarm_cs_sec_d2);
            break;
        }
        default: {
            status_ = Q_SUPER(&Clock_Alarm_Settings);
            break;
        }
    }
    return status_;
}

//${HSMs::Clock_Alarm::SM::Clock::Settings::cs_format} .......................
static QState Clock_Alarm_cs_format(Clock_Alarm * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${HSMs::Clock_Alarm::SM::Clock::Settings::cs_format::SET}
        case SET_SIG: {
            if (me->temp_format == FORMAT_24H) {
                me->temp_format = FORMAT_AM;
            } else if(me->temp_format == FORMAT_AM) {
                me->temp_format = FORMAT_PM;
            } else if(me->temp_format == FORMAT_PM) {
                me->temp_format = FORMAT_24H;
            }
            Clock_Alarm_display_clock_setting_time(me, CLOCK_SETTING_TIME_ROW, CLOCK_SETTING_TIME_COL);
            status_ = Q_HANDLED();
            break;
        }
        //${HSMs::Clock_Alarm::SM::Clock::Settings::cs_format::OK}
        case OK_SIG: {
            if (me->temp_format != FORMAT_24H) {
                me->temp_time = convert_12hformat_to_24h(me->temp_time, (time_format_t)me->temp_format);
                me->time_mode = MODE_12H;
            } else {
                me->time_mode = MODE_24H;
            }

            me->temp_time *= 10UL;
            Clock_Alarm_set_curr_time(me->temp_time);
            //${HSMs::Clock_Alarm::SM::Clock::Settings::cs_format::OK::[is_time_set_error(me->temp_time~}
            if (is_time_set_error(me->temp_time, (time_format_t) me->temp_format)) {
                status_ = Q_TRAN(&Clock_Alarm_cs_error);
            }
            else {
                status_ = Q_UNHANDLED();
            }
            break;
        }
        default: {
            status_ = Q_SUPER(&Clock_Alarm_Settings);
            break;
        }
    }
    return status_;
}

//${HSMs::Clock_Alarm::SM::Clock::Settings::cs_min_d2} .......................
static QState Clock_Alarm_cs_min_d2(Clock_Alarm * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${HSMs::Clock_Alarm::SM::Clock::Settings::cs_min_d2}
        case Q_ENTRY_SIG: {
            me->temp_digit = DIGIT2(GET_MIN(me->temp_time));
            status_ = Q_HANDLED();
            break;
        }
        //${HSMs::Clock_Alarm::SM::Clock::Settings::cs_min_d2::SET}
        case SET_SIG: {
            ++me->temp_digit;
            me->temp_digit %= 10;
            me->temp_time -= DIGIT2(GET_MIN(me->temp_time)) * 60UL;
            me->temp_time += (me->temp_digit) * 60UL;
            Clock_Alarm_display_clock_setting_time(me, CLOCK_SETTING_TIME_ROW, CLOCK_SETTING_TIME_COL);
            // display_set_cursor(CLOCK_SETTING_TIME_ROW, CLOCK_SETTING_TIME_D1_COL);
            status_ = Q_HANDLED();
            break;
        }
        //${HSMs::Clock_Alarm::SM::Clock::Settings::cs_min_d2::OK}
        case OK_SIG: {
            status_ = Q_TRAN(&Clock_Alarm_cs_sec_d1);
            break;
        }
        default: {
            status_ = Q_SUPER(&Clock_Alarm_Settings);
            break;
        }
    }
    return status_;
}

//${HSMs::Clock_Alarm::SM::Clock::Settings::cs_min_d1} .......................
static QState Clock_Alarm_cs_min_d1(Clock_Alarm * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${HSMs::Clock_Alarm::SM::Clock::Settings::cs_min_d1}
        case Q_ENTRY_SIG: {
            me->temp_digit = DIGIT1(GET_MIN(me->temp_time));
            status_ = Q_HANDLED();
            break;
        }
        //${HSMs::Clock_Alarm::SM::Clock::Settings::cs_min_d1::SET}
        case SET_SIG: {
            ++me->temp_digit;
            me->temp_digit %= 6;
            me->temp_time -= DIGIT1(GET_MIN(me->temp_time)) * 10UL * 60UL;
            me->temp_time += (me->temp_digit)  * 10UL * 60UL;
            Clock_Alarm_display_clock_setting_time(me, CLOCK_SETTING_TIME_ROW, CLOCK_SETTING_TIME_COL);
            // display_set_cursor(CLOCK_SETTING_TIME_ROW, CLOCK_SETTING_TIME_D1_COL);
            status_ = Q_HANDLED();
            break;
        }
        //${HSMs::Clock_Alarm::SM::Clock::Settings::cs_min_d1::OK}
        case OK_SIG: {
            status_ = Q_TRAN(&Clock_Alarm_cs_min_d2);
            break;
        }
        default: {
            status_ = Q_SUPER(&Clock_Alarm_Settings);
            break;
        }
    }
    return status_;
}

//${HSMs::Clock_Alarm::SM::Clock::Clock_Setting} .............................
static QState Clock_Alarm_Clock_Setting(Clock_Alarm * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = Q_SUPER(&Clock_Alarm_Clock);
            break;
        }
    }
    return status_;
}

//${HSMs::Clock_Alarm::SM::Alarm_Notify} .....................................
static QState Clock_Alarm_Alarm_Notify(Clock_Alarm * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${HSMs::Clock_Alarm::SM::Alarm_Notify::initial}
        case Q_INIT_SIG: {
            status_ = Q_TRAN(&Clock_Alarm_alarm_msg_on);
            break;
        }
        //${HSMs::Clock_Alarm::SM::Alarm_Notify::OK}
        case OK_SIG: {
            status_ = Q_TRAN_HIST(me->hist_Clock);
            break;
        }
        //${HSMs::Clock_Alarm::SM::Alarm_Notify::TICK}
        case TICK_SIG: {
            Clock_Alarm_display_curr_time(me, TICKING_CURR_TIME_ROW, TICKING_CURR_TIME_COL);
            //${HSMs::Clock_Alarm::SM::Alarm_Notify::TICK::[++me->alarm_timeout>=200U]}
            if (++me->alarm_timeout >= 200U) {
                me->alarm_timeout = 0U;
                status_ = Q_HANDLED();
            }
            else {
                status_ = Q_UNHANDLED();
            }
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${HSMs::Clock_Alarm::SM::Alarm_Notify::alarm_msg_on} .......................
static QState Clock_Alarm_alarm_msg_on(Clock_Alarm * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${HSMs::Clock_Alarm::SM::Alarm_Notify::alarm_msg_on}
        case Q_ENTRY_SIG: {
            bsp_display_write_string(15, 15, "**ALARM**");
            status_ = Q_HANDLED();
            break;
        }
        //${HSMs::Clock_Alarm::SM::Alarm_Notify::alarm_msg_on::TICK}
        case TICK_SIG: {
            me->timeout++;
            //${HSMs::Clock_Alarm::SM::Alarm_Notify::alarm_msg_on::TICK::[me->timeout==10]}
            if (me->timeout == 10) {
                me->timeout = 0;
                status_ = Q_TRAN(&Clock_Alarm_alarm_msg_off);
            }
            else {
                status_ = Q_UNHANDLED();
            }
            break;
        }
        default: {
            status_ = Q_SUPER(&Clock_Alarm_Alarm_Notify);
            break;
        }
    }
    return status_;
}

//${HSMs::Clock_Alarm::SM::Alarm_Notify::alarm_msg_off} ......................
static QState Clock_Alarm_alarm_msg_off(Clock_Alarm * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${HSMs::Clock_Alarm::SM::Alarm_Notify::alarm_msg_off}
        case Q_ENTRY_SIG: {
            bsp_display_clear();
            status_ = Q_HANDLED();
            break;
        }
        //${HSMs::Clock_Alarm::SM::Alarm_Notify::alarm_msg_off::TICK}
        case TICK_SIG: {
            //${HSMs::Clock_Alarm::SM::Alarm_Notify::alarm_msg_off::TICK::[0]}
            if (0) {
                status_ = Q_TRAN(&Clock_Alarm_alarm_msg_on);
            }
            else {
                status_ = Q_UNHANDLED();
            }
            break;
        }
        default: {
            status_ = Q_SUPER(&Clock_Alarm_Alarm_Notify);
            break;
        }
    }
    return status_;
}
//$enddef${HSMs::Clock_Alarm} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

// ISR() {
//     Clock_Alarm_update_curr_time();
// }


// HELPER FUNCTIONS

/*
 * Description : Decodes AM/PM information from given time in 24H format
 * param1: Integer time in 24H format
 * return : A string value("AM" or "PM")
 */
const char* get_am_or_pm(uint32_t time24h) {
    const char* ampm;
    uint8_t h = GET_HOUR(time24h);
    if(h == 0U){
        ampm = "AM";
    }else if( h > 12U){
        ampm = "PM";
    }else if (h == 12U)
        ampm = "PM";
    else
        ampm = "AM";
    return ampm;
}

/*
 * Description: Converts given integer time in 12H format to integer time 24H format
 * param1 : Integer time in 12H format
 * param2 : time format of type time_format_t
 * return : Integer time in 24H format
 */
uint32_t convert_12hformat_to_24h(uint32_t time12h, time_format_t ampm) {
    uint8_t hour;
    uint32_t time24h;
    hour = GET_HOUR(time12h);
    if(ampm == FORMAT_AM){
        time24h = (hour == 12)? (time12h-(12UL * 3600UL)) : time12h;
    }else{
        time24h = (hour == 12)? time12h : (time12h +(12UL * 3600UL));
    }
    return time24h;
}

/*
 * Description: Converts given integer time in 24H format to integer time 12H format
 * param1 : Integer time in 24H format
 * return : Integer time in 12H format
 */
uint32_t convert_24hformat_to_12h(uint32_t time24h) {
    uint8_t hour;
    uint32_t time12h;
    hour = GET_HOUR(time24h);

    if(hour == 0)
        time12h = time24h + (12UL * 3600UL);
    else{
        if((hour < 12UL) || (hour == 12UL))
            return time24h;
        else
            time12h = time24h - (12UL * 3600UL);
    }
    return time12h;
}

bool is_time_set_error(uint32_t time_, time_format_t format) {
    uint8_t h = GET_HOUR(time_);
    return ( (h > 23) || ( (h > 12) || (h == 0)) && format != FORMAT_24H);
}
