//$file${HSMs::./src::ClockAlarm_SM.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: model.qm
// File:  ${HSMs::./src::ClockAlarm_SM.h}
//
// This code has been generated by QM 7.0.3 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${HSMs::./src::ClockAlarm_SM.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#ifndef CLOCK_ALARM_H
#define CLOCK_ALARM_H

enum Clock_Alarm_Signals {
    SET_SIG = Q_USER_SIG,
    OK_SIG,
    ABRT_SIG,
    ALARM_SIG,
    TICK_SIG,
    MAX_SIG
};

enum time_mode {
    MODE_24H,
    MODE_12H
};

enum alarm_status {
    ALARM_OFF,
    ALARM_ON
};

typedef enum time_format {
    FORMAT_24H,
    FORMAT_AM,
    FORMAT_PM
} time_format_t;

#define GET_HOUR(seconds)     (seconds / 3600UL)
#define GET_MIN(seconds)      ( (seconds / 60UL) % 60UL)
#define GET_SEC(seconds)      (seconds % 60UL)
#define DIGIT1(d)             (d / 10U)
#define DIGIT2(d)             (d % 10U)

#define MAX_TIME (864000UL) // 24 * 3600 * 10
#define INITIAL_CURR_TIME  (((4UL * 3600UL) + (0UL * 60UL) + 0UL) * 10UL)
#define INITIAL_ALARM_TIME (8UL * 3600UL)

#define TICKING_CURR_TIME_ROW 0
#define TICKING_CURR_TIME_COL 3
#define CLOCK_CURR_TIME_ROW 0
#define CLOCK_CURR_TIME_COL 2
#define CLOCK_SETTING_TIME_ROW 0
#define CLOCK_SETTING_TIME_COL 2
//
#define CLOCK_SETTING_TIME_HOUR_D1_COL 2
#define CLOCK_SETTING_TIME_HOUR_D2_COL 3
#define CLOCK_SETTING_TIME_MIN_D1_COL  5
#define CLOCK_SETTING_TIME_MIN_D2_COL  6
#define CLOCK_SETTING_TIME_SEC_D1_COL  8
#define CLOCK_SETTING_TIME_SEC_D2_COL  9

#define CS_ROW 0
#define CS_HOUR_D1_COL 2


//$declare${HSMs::Clock_Alarm_ctor} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${HSMs::Clock_Alarm_ctor} ..................................................
void Clock_Alarm_ctor(void);
//$enddecl${HSMs::Clock_Alarm_ctor} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$declare${HSMs::super_ClockAlarm} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${HSMs::super_ClockAlarm} ..................................................
extern QHsm *const super_ClockAlarm;
//$enddecl${HSMs::super_ClockAlarm} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#endif
