//$file${HSMs::./src::ClockAlarm_SM.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: model.qm
// File:  ${HSMs::./src::ClockAlarm_SM.c}
//
// This code has been generated by QM 7.0.3 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${HSMs::./src::ClockAlarm_SM.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpc.h"
#include "bsp.h" // display
#include "ClockAlarm_SM.h"
//$declare${HSMs::Clock_Alarm} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${HSMs::Clock_Alarm} .......................................................
typedef struct Clock_Alarm {
// protected:
    QHsm super;

// private:
    uint8_t temp_time;
    uint32_t alarm_time;
    uint8_t alarm_status;
    uint8_t time_mode;

// private state histories
    QStateHandler hist_Clock;
} Clock_Alarm;

extern uint32_t Clock_Alarm_curr_time;

extern Clock_Alarm Clock_Alarm_obj;

// public:
static uint32_t Clock_Alarm_get_curr_time(void);
static void Clock_Alarm_update_curr_time(void);

// protected:
static QState Clock_Alarm_initial(Clock_Alarm * const me, void const * const par);
static QState Clock_Alarm_Clock(Clock_Alarm * const me, QEvt const * const e);
static QState Clock_Alarm_Ticking(Clock_Alarm * const me, QEvt const * const e);
static QState Clock_Alarm_Settings(Clock_Alarm * const me, QEvt const * const e);
static QState Clock_Alarm_Clock_Setting(Clock_Alarm * const me, QEvt const * const e);
static QState Clock_Alarm_Alarm_Setting(Clock_Alarm * const me, QEvt const * const e);
static QState Clock_Alarm_Alarm_Notify(Clock_Alarm * const me, QEvt const * const e);
//$enddecl${HSMs::Clock_Alarm} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 800U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 8.0.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${HSMs::Clock_Alarm} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${HSMs::Clock_Alarm} .......................................................
uint32_t Clock_Alarm_curr_time;
Clock_Alarm Clock_Alarm_obj;

//${HSMs::Clock_Alarm::update_curr_time} .....................................
static void Clock_Alarm_update_curr_time(void) {
    if(++Clock_Alarm_curr_time == MAX_TIME) {
        Clock_Alarm_curr_time = 0;
    }
}

//${HSMs::Clock_Alarm::SM} ...................................................
static QState Clock_Alarm_initial(Clock_Alarm * const me, void const * const par) {
    //${HSMs::Clock_Alarm::SM::initial}
    // state history attributes
    me->hist_Clock = Q_STATE_CAST(&Clock_Alarm_Ticking);
    return Q_TRAN(&Clock_Alarm_Ticking);
}

//${HSMs::Clock_Alarm::SM::Clock} ............................................
static QState Clock_Alarm_Clock(Clock_Alarm * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${HSMs::Clock_Alarm::SM::Clock}
        case Q_EXIT_SIG: {
            // save deep history
            me->hist_Clock = QHsm_state(Q_HSM_UPCAST(me));
            status_ = Q_HANDLED();
            break;
        }
        //${HSMs::Clock_Alarm::SM::Clock::ALARM}
        case ALARM_SIG: {
            status_ = Q_TRAN(&Clock_Alarm_Alarm_Notify);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${HSMs::Clock_Alarm::SM::Clock::Ticking} ...................................
static QState Clock_Alarm_Ticking(Clock_Alarm * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${HSMs::Clock_Alarm::SM::Clock::Ticking::SET}
        case SET_SIG: {
            status_ = Q_TRAN(&Clock_Alarm_Clock_Setting);
            break;
        }
        //${HSMs::Clock_Alarm::SM::Clock::Ticking::OK}
        case OK_SIG: {
            status_ = Q_TRAN(&Clock_Alarm_Alarm_Setting);
            break;
        }
        default: {
            status_ = Q_SUPER(&Clock_Alarm_Clock);
            break;
        }
    }
    return status_;
}

//${HSMs::Clock_Alarm::SM::Clock::Settings} ..................................
static QState Clock_Alarm_Settings(Clock_Alarm * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${HSMs::Clock_Alarm::SM::Clock::Settings::ABRT}
        case ABRT_SIG: {
            status_ = Q_TRAN(&Clock_Alarm_Ticking);
            break;
        }
        //${HSMs::Clock_Alarm::SM::Clock::Settings::OK}
        case OK_SIG: {
            status_ = Q_TRAN(&Clock_Alarm_Ticking);
            break;
        }
        default: {
            status_ = Q_SUPER(&Clock_Alarm_Clock);
            break;
        }
    }
    return status_;
}

//${HSMs::Clock_Alarm::SM::Clock::Settings::Clock_Setting} ...................
static QState Clock_Alarm_Clock_Setting(Clock_Alarm * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = Q_SUPER(&Clock_Alarm_Settings);
            break;
        }
    }
    return status_;
}

//${HSMs::Clock_Alarm::SM::Clock::Settings::Alarm_Setting} ...................
static QState Clock_Alarm_Alarm_Setting(Clock_Alarm * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = Q_SUPER(&Clock_Alarm_Settings);
            break;
        }
    }
    return status_;
}

//${HSMs::Clock_Alarm::SM::Alarm_Notify} .....................................
static QState Clock_Alarm_Alarm_Notify(Clock_Alarm * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${HSMs::Clock_Alarm::SM::Alarm_Notify::OK}
        case OK_SIG: {
            status_ = Q_TRAN_HIST(me->hist_Clock);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
//$enddef${HSMs::Clock_Alarm} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
